name: SPARQ
description: A event listener app for people with memory loss conditions.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  add_2_calendar: ^2.1.0
  http: ^0.13.4

  shared_preferences: ^2.0.0
  flutter:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"

  speech_to_text:
    path: ../speech_to_text


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
    - assets/verbs.txt
